### ISSUE TITLE
fxn Lavatory

### ISSUE THREAD

**Issue by GwennyB** [Megga-Miister/Diamond-Lavs#13]
CONSTRUCTOR PROPERTIES:
lat
lng
address
votesTotal
votesClean
votesEasyToFind
homeDB
status
statusReason

OUTPUTS:
constructed object

NOTES:
confirm selected properties
determine default values
establish data formats for all properties

**Comment by GurinderB** [comment]
This task has been completed.

**Comment by Megga-Miister** [comment]
# #28
